import type { Metadata } from "next";
import dynamic from "next/dynamic";

import { inter, bauhaus, gotham, spaceGrotesk } from "@/fonts/fonts";
import "./globals.css";
import HeaderWrapper from "@/components/header/header-wrapper";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${bauhaus.variable} ${gotham.variable} ${spaceGrotesk.variable}`}
      >
        <>
          <HeaderWrapper />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
